services:
  task-tracker-db:
    image: postgres
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass!
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "15432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "email-sending-tasks:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    ports:
      - "2181:2181"

volumes:
  db-data:
