server:
  port: 8080
spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: pass!
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog.xml
